### ISSUE TITLE
What happens when connected to the wrong network

### ISSUE THREAD

**Issue by carver** [kayagoban/shadowlands#4]
It doesn't look like the connection and network ID are being enforced in line 78: https://github.com/kayagoban/shadowlands/blob/dbe831e9889ce36a5784347ea1e29d22a87ab66a/debian/shadowlands_1_all__dbp__/usr/local/bin/shadowlands#L76-L80

Am I missing something?

**Comment by kayagoban** [comment]
Yep, you’re right, that’s a check that’s not doing anything.  Thanks for the report!

**Comment by kayagoban** [comment]
Now that I take a second look, I remember the meaning behind this.  

When importing web3.auto.infura goes wrong, a call to w3.version.network will often result in an exception.  The fallback is hoping for a connection to a local node.

this probably could be shortened to something like:

    try:
        from web3.auto.infura import w3
        w3.version.network
    except Exception: 
        from web3.auto import w3
    
    if not (w3.isConnected() and w3.version.network == '1'):
    	print("Could not get an eth node to bootstrap from, exiting.")
    	sys.exit(1)

Functionally it’s similar but clearer because no useless equality tests are being done.

**Comment by kayagoban** [comment]
This script no longer exists :)
