### ISSUE TITLE
Shadowlands pip package

### ISSUE THREAD

**Issue by carver** [kayagoban/shadowlands#5]
It would be really cool if I could download the shadowlands package directly in pip. The idea of validating the package using an on-chain registry is awesome, though. The registry could host the exact pip version, instead of having the zip url. (keeping a checksum, of course)

A big reason I want this is to personally verify what shadowlands is doing on install. It takes longer to read through the debian packaging and bootstrap script than it would a more traditional pip installation. (at least for me)

**Comment by kayagoban** [comment]
Yes, I had a feeling I might disrupt the fabric of the python universe by shunning pypi.org for my own package registry.  I’ll try to explain my reasons behind this.

The concept is for Shadowlands to be an on-demand, live piece of software, more like a website than a semipermanently installed piece of software.  This requires the same level of trust required for any of the SLDapps that Shadowlands acts as a platform to.  It may be different every time you run it, but you at least know who it’s coming from (if you bothered to find out).  The openness is there, because the zip files contain all of the source code, and the accountability is there, because I registered the checksum with my own key. 

I do feel like the combined install/loading script is overwrought.  I believe I have found a way to bootstrap a python virtual env within a running python process - if I use that, I can stop wrapping a heredoc’d python script inside a bash script, which does not sit well with me.  Then, the loading script with be pure python, and, I think, easier to understand.

**Comment by kayagoban** [comment]
I think what I’m leaning towards is making the shadowlands loader purely python-based and pip-installable.  

The wrapped heredoc solution works but is painfully clumsy and too opaque.  I want the script to be short and clear enough for any python programmer to understand on a first viewing.

**Comment by kayagoban** [comment]
I'm abandoning this for now, since at least on linux there are system level scripts that need to be set to access the USB devices.  I can't do this with pip alone.
